- name: Create gmaster user
  user:
    name: gmaster
    group: gmaster
    password: "{{ 'zjvl' + '@' + 'aktmxj' + ansible_default_ipv4.address | regex_search('[0-9]{2}$') + '!'}}"
  when: "{{ ansible_default_ipv4.address | regex_search('[0-9]{2}$') }}"
