- name: Create gmaster user
  command: echo  "{{ ansible_default_ipv4.address | regex_replace('[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.') }}"
  register: myPass

- name: echo myPass
  command: echo "{{ myPass.stdout }}"
