- name: Create gmaster user
  set_stats:
    data:
      myPass : {{ ansible_default_ipv4.address | regex_replace('[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.') }}

- name: echo value
  command: echo "{{ myPass }}"
