- name: Create gmaster user
  user:
    name: gmaster
    group: gmaster
    password: "{{ 'zjvl' + '@' + 'aktmxj' + {{ ansible_default_ipv4.address | regex_replace('[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.')}} + '!'}}"
