- name: Create gmaster user
  vars:
    myPass: "{{ ansible_default_ipv4.address | regex_replace('[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.') | regex_search('[0-9]{2}$') }}"
    prePass: "zjvl@aktmxj{}"
    postPass: "!"
  user:
    name: gmaster
    password: "{{ prePass + '0' + myPass + postPass}}"
  when: "{{ myPass | regex_search('[0-9]{1}$') }}"

  user:
    name: gmaster
    password: "{{ prePass + myPass + postPass }}"
  when: "{{ myPass | regex_search('[0-9]{2}$') }}"
